import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EAE8FF', 
    justifyContent: 'center',
    alignItems: 'center',  
  },
  expenseCalculatorContainer: {
    width: '100%',
    alignItems: 'center',  
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#5E17EB',  
    marginBottom: 50,  
  },
  cardContainer: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',  
    justifyContent: 'space-evenly',  
    marginBottom: 30,
  },
  card: {
    backgroundColor: '#5E17EB',  
    borderRadius: 10,
    width: '45%',  
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    shadowColor: '#000',  
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardTitle: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  cardValue: {
    fontSize: 36,
    color: '#fff',
    fontWeight: 'bold',
  },
  picker: {
    height: 40,
    width: '80%',
    borderColor: '#EAE8FF',  
    borderWidth: 1,
    borderRadius: 5,
    marginVertical: 10,
    backgroundColor: '#FFFFFF',
    marginBottom: 10,
  },
  input: {
    height: 40,
    width: '80%',
    borderRadius: 5,
    paddingLeft: 10,
    marginVertical: 10,
    backgroundColor: '#FFFFFF',
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#EAE8FF',  
    borderColor: '#5E17EB',
    borderWidth: 2,
    paddingVertical: 12,
    paddingHorizontal: 60,
    borderRadius: 5,
  },
  buttonText: {
    color: '#5E17EB',
    fontSize: 18,
    fontWeight: 'bold',
  },
  footerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
    backgroundColor: '#5E17EB',
    paddingVertical: 10,
    position: 'absolute',
    bottom: 0, 
  },
  footerButton: {
    paddingVertical: 12,
    borderRadius: 5,
    width: '40%', 
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
})
